# This is a basic workflow to help you get started with Actions

name: Analyze code statically

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  brakeman:
    runs-on: ubuntu-latest
    env:
      ANALYZER: '@moneyforward/code-review-action-brakeman-plugin'
      ANALYZER_VERSION: '~0'
    steps:
      - uses: actions/checkout@v2
      - run: sudo npm i -g --no-save "${ANALYZER}@${ANALYZER_VERSION}"
      - id: node-env
        run: echo "::set-output name=path::$(npm root -g)"
      - name: Analyze code statically
        uses: moneyforward/code-review-action@v0
        env:
          NODE_PATH: ${{ steps.node-env.outputs.path }}
        with:
          analyzer: ${{ env.ANALYZER }}
