name: CI/CD Example # workflow name

on: # attribute determines how workflow gets triggered
  push: # triggers on a`push` to the `main` branch
    branches: [ main ]
  workflow_dispatch: # triggers manually
defaults : 
    run:
     working-directory: ./my-app
jobs:
  build: # job 1 identifier
    name: Build
    runs-on: ubuntu-latest
   

    steps:
    - name: Clone repo & checkout code
      uses: actions/checkout@v2 
      # this action allows the runner to access your code by cloning it

    - name: Install Node.js
      uses: actions/setup-node@v2.4.0
      # installs and sets up Node environment in our runner
      with:
        node-version: 14.x

    - name: Install NPM packages
      run: npm install
      # similar to npm install, for automated environments

    - name: Build project
      run: npm run build # command to build project

    - name: Run tests
      run: npm run test # command to run tests

    - name: Upload production-ready build files
      uses: actions/upload-artifact@v2 
      # uploads build files to be accessible across jobs
      with:
        name: production
        path: ./my-app/build

  deploy: # job 2 identifier
    name: Deploy
    needs: build 
    # the build job must succeed in order to run this job
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2 
      # downloads the uploaded build files
      with:
        name: production
        path: ./build

    - name: Deploy to Github pages
      uses: crazy-max/ghaction-github-pages@v2
      # action to deploy to GitHub Pages
      with:
        target_branch: gh-pages
        build_dir: ./build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # default secret for auth

  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v6
        with:
          stale-issue-message: 'This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 5 days.'
          stale-pr-message: 'This PR is stale because it has been open 45 days with no activity. Remove stale label or comment or this will be closed in 10 days.'
          close-issue-message: 'This issue was closed because it has been stalled for 5 days with no activity.'
          close-pr-message: 'This PR was closed because it has been stalled for 10 days with no activity.'
          days-before-issue-stale: 30
          days-before-pr-stale: 45
          days-before-issue-close: 5
          days-before-pr-close: 10 
          stale-issue-label: 'no-issue-activity'
