name: jobs2-dependencies-workshop
on: 
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch: 
jobs:
  job1:
    env:
      JOB1_VARIABLE: "THIS IS THE VARIABLE FOR JOB1"
    strategy:
      matrix:
        version: [10,12,14]
        os: [ubuntu-latest,windows-latest,macOS-latest]
    runs-on: ${{matrix.os}}
    steps:
      - run: echo "$JOB1_VARIABLE"
  job2:
    env:
      JOB2_VARIABLE: "THIS IS THE VARIABLE FOR JOB2"
    strategy:
      matrix:
        version: [10,12,14]
        os: [windows-latest,macOSlatest,ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
    - run: ./server.sh
  job3: 
    needs: job2
    strategy:
      matrix: 
        version: [10,12,14]
        os: [windows-latest,macOSlatest,ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
     - run: echo "JOB 3 ONLY RUNS IF JOB 2 SUCCEEDS"
  job4: 
    if: always()
    needs: job2
    strategy:
      matrix:
        version: [10, 12, 14]
        os: [ubuntu-latest, windows-latest,macOS-latest]
    runs-on: ${{matrix.os}}
    steps:
     - run: echo "JOB4 RUNS EVEN AFTER JOB2 FAILS"
    
    
